Fix ros2
ros2/turtlebot2_demo pull request #98
Opened 2019-08-11 23:35 UTC by Karsten1987

updated API for dashing

2019-09-12 13:23 UTC, clalancette requested changes
Looks generally OK to me, with a few things to fix.

2019-09-12 13:23 UTC, clalancette commented on depthimage_to_pointcloud2/src/depthimage_to_pointcloud2_node.cpp
> +  g_pub_point_cloud->publish(*cloud_msg);
Instead of doing this, I think I'd prefer to make `cloud_msg` a `unique_ptr`, then use `std::move` here instead.

2019-09-12 13:23 UTC, clalancette commented on turtlebot2_drivers/src/kobuki_node.cpp
> +  parameters.device_port = "/dev/ttyUSB0";
Why this change?  If you have the udev rules setup properly, `/dev/kobuki` should exist.  Also, we may want to make this a parameter on the node so it is configurable, but we don't need to do that in this PR.

2019-09-12 13:23 UTC, clalancette commented on turtlebot2_drivers/src/kobuki_node.cpp
> +    for (auto i = 0u; i < odom_msg.pose.covariance.size(); ++i) {
I prefer not to use `auto` here, though the type *was* wrong before; I think it should be `size_t`.

2019-10-17 13:12 UTC, surfertas commented
Hi will this be merged soon?

2019-10-17 20:51 UTC, clalancette commented
> Hi will this be merged soon?

@Karsten1987 will have to respond to my comments, but this is mostly blocked on getting https://github.com/yujinrobot/kobuki_core/pull/41 and/or https://github.com/yujinrobot/kobuki_core/pull/43 merged.

2022-09-13 15:27 UTC, clalancette commented
Closing to archive this repository.

2022-09-13 15:27 UTC, closed without merging